version: 2
multi-ecosystem-groups:
  weekly-updates:
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    labels:
      - "PR Type: Maintenance"
    pull-request-branch-name:
      separator: "-"
    groups:
      version-updates:
          patterns:
             - "*"
          update-types:
            - "minor"
            - "patch"

updates:
  - package-ecosystem: "github-actions"
    multi-ecosystem-group: "weekly-updates"
    patterns: ["*"]
    directory: "/"

  - package-ecosystem: "gradle"
    multi-ecosystem-group: "weekly-updates"
    patterns: ["*"]
    directory: "/platforms/android/project"

  - package-ecosystem: "npm"
    multi-ecosystem-group: "weekly-updates"
    patterns: ["*"]
    directory: "/platforms/web/"
