[versions]
androidGradlePlugin = "8.13.2"
androidxFragment = "1.8.9"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidAssetPack = { id = "com.android.asset-pack", version.ref = "androidGradlePlugin" }

[libraries]
androidxFragment = { module = "androidx.fragment:fragment", version.ref = "androidxFragment" }
